apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/replicas
      value: 1
  target:
    group: apps.openshift.io
    kind: DeploymentConfig
    name: hunt-backend
    version: v1
- patch: |-
    - op: replace
      path: /spec/host
      value: 1
  target:
    group: apps.openshift.io
    kind: DeploymentConfig
    name: hunt-backend
    version: v1

resources:
- ../../base
