apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    image.openshift.io/triggers: |-
      [
        {
          "from": {
            "kind": "ImageStreamTag",
            "name": "hunt-backend:latest"
          },
          "fieldPath": "spec.template.spec.containers[0].image"
        }
      ]
  labels:
    component: backend
  name: hunt-backend
spec:
  replicas: 3
  selector:
    matchLabels:
      deployment: hunt-backend
  template:
    metadata:
      labels:
        deployment: hunt-backend
        app: pod-hunt
    spec:
      serviceAccountName: ripper
      containers:
        - image: 'ghcr.io/vrutkovs/k8s-podhunt-backend'
          imagePullPolicy: Always
          name: hunt-backend
          ports:
            - containerPort: 8080
              protocol: TCP
