apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../production

patchesJson6902:
- patch: |-
    - op: replace
      path: /spec/host
      value: duckhunt.apps.vrutkovs-demo.origin-gce.dev.openshift.com
  target:
    group: route.openshift.io
    kind: Route
    name: backend
    version: v1
- patch: |-
    - op: replace
      path: /spec/host
      value: duckhunt.apps.vrutkovs-demo.origin-gce.dev.openshift.com
  target:
    group: route.openshift.io
    kind: Route
    name: ui
    version: v1
