apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-ui
  namespace: pod-hunt
  labels:
    app: hunt-ui
spec:
  lookupPolicy:
    local: false
  tags:
  - name: nginx
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/nginx-118
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: nodejs
    from:
      kind: DockerImage
      name: registry.access.redhat.com/ubi8/nodejs-14
    importPolicy: {}
    referencePolicy:
      type: Local
  - name: src
    importPolicy: {}
    referencePolicy:
      type: Source
  - name: webserver
    importPolicy: {}
    referencePolicy:
      type: Source
