---
apiVersion: build.dev/v1alpha1
kind: BuildRun
metadata:
  generateName: ui-buildrun-
  namespace: pod-hunt
  annotations:
    argocd.argoproj.io/hook: PostSync
spec:
  buildRef:
    name: ui-build
  serviceAccount:
    name: pipeline
