---
apiVersion: build.dev/v1alpha1
kind: BuildRun
metadata:
  generateName: backend-buildrun-
  namespace: pod-hunt
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  buildRef:
    name: backend-build
  serviceAccount:
    name: pipeline
