---
$patch: delete
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    component: ui
  name: hunt-ui-src
---
$patch: delete
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    component: ui
  name: hunt-ui-bin
---
$patch: delete
apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  labels:
    component: backend
  name: hunt-backend-src
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-ui
  labels:
    component: ui
spec:
  lookupPolicy:
    local: false
  $patch: delete
  tags: []
---
apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  name: hunt-backend
  labels:
    component: backend
spec:
  lookupPolicy:
    local: false
  $patch: delete
  tags: []
